---
- hosts: all
  sudo: yes
  tasks:
  - name: install nginx
    apt: name=nginx state=latest
  - name: install zsh
    apt: name=zsh state=latest
  - name: install wget
    apt: name=wget state=latest         
  - name: clone web site
    shell: git clone https://github.com/alirni/Under-Construction.git
  - name: copy v catalog saita
    command: cp -r /root/Under-Construction/. /var/www/
    command: rm -r /root/Under-Construction/
  - name: edit nginx
    template:
      src: default
      dest: "/etc/nginx/sites-available/"
  - name: start nginx
    service: name=nginx state=started enabled=yes
  - name: edit sysctl
    template:
      src: sysctl.conf
      dest: "/etc/"
  - name: Set authorized key taken from file
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  - name: Set authorized key taken from file 2
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa2.pub') }}"
  - name: reboot system
    command: reboot
